# Generated by Django 2.2.16 on 2020-10-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0014_fix_nan_value_for_global_speed'),
        ('courseware', '0008_index_module_id_grade_student_id'),
    ]

    operations = [
    ]
